services:
  - type: web
    name: crm-core-api
    runtime: docker
    plan: free
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    buildFilter:
      paths:
        - apps/api/**
        - packages/contract/**
        - pnpm-lock.yaml
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
